---
title: Wittywines
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
gems:
- octopress-minify-html
- jekyll-admin
